spring:
  #application:
    #name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: VinceCar@125
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
    org.hibernate: WARN

server:
  port: 8081

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
